export const Rooms = [
  { id: 1, RoomNumber: 101, floor: 1 },
  { id: 2, RoomNumber: 102, floor: 1 },
  { id: 3, RoomNumber: 103, floor: 1 },
  { id: 4, RoomNumber: 104, floor: 1 },
  { id: 5, RoomNumber: 109, floor: 1 },
  { id: 6, RoomNumber: 110, floor: 1 },
  { id: 7, RoomNumber: 105, floor: 1 },
  { id: 8, RoomNumber: 106, floor: 1 },
  { id: 9, RoomNumber: 107, floor: 1 },
  { id: 10, RoomNumber: 108, floor: 1 },
  { id: 11, RoomNumber: 111, floor: 1 },
];

export const FeedBack = [
  { id: 1, 
    dateTime: "05-05-24  11:49 AM", 
    message:"Some of the computers in the lab 1 is not working.", 
    status: "unread" 
  },
  { id: 2, 
    dateTime: "04-26-24  11:49 AM", 
    message:"1 electric fan in room 123 overheated.", 
    status: "unread" 
  },
  { id: 3, 
    dateTime: "04-26-24  11:49 AM", 
    message:"1 electric fan in room 123 overheated.", 
    status: "unread" 
  },
  { id: 4, 
    dateTime: "05-05-24  11:49 AM", 
    message:"Some of the computers in the lab 1 is not working.", 
    status: "read" 
  },
  { id: 5, 
    dateTime: "04-26-24  11:49 AM", 
    message:"1 electric fan in room 123 overheated.", 
    status: "read" 
  },
  { id: 6, 
    dateTime: "04-26-24  11:49 AM", 
    message:"1 electric fan in room 123 overheated.", 
    status: "read" 
  },
];

export const ActivityLog = [
  { id: 20000000, 
    dateTime: "May 2, 2024 15:34:25 PM", 
    activities:"Maira Bermudez timed in at multimedia.", 
  },
  { id: 20000001, 
    dateTime: "May 2, 2024 17:34:25 PM", 
    activities:"Maira Bermudez timed out at multimedia.", 
  },
  { id: 20000002, 
    dateTime: "May 4, 2024 13:34:25 PM", 
    activities:"Maribel Garcia timed in at mpg2.", 
  },
  { id: 20000003, 
    dateTime: "May 4, 2024 15:34:25 PM", 
    activities:"Maribel Garcia timed out at mpg2.", 
  },
  { id: 20000004, 
    dateTime: "May 5, 2024 13:34:25 PM", 
    activities:"Juan Dela Cruz timed in at room 123.", 
  },
];

export const Notification = [
  { id: 1, 
    dateTime: "05-05-24  11:49 AM", 
    message:"You have feedback. Check it now.", 
    status: "unread" 
  },
  { id: 2, 
    dateTime: "05-04-24  11:49 AM", 
    message:"You have feedback. Check it now.", 
    status: "unread" 
  },
  { id: 3, 
    dateTime: "05-03-24  11:49 AM", 
    message:"You have feedback. Check it now.", 
    status: "unread" 
  },
  { id: 4, 
    dateTime: "04-26-24  11:49 AM", 
    message:"You have feedback. Check it now.", 
    status: "read" 
  },
  { id: 5, 
    dateTime: "04-25-24  11:49 AM", 
    message:"You have feedback. Check it now.", 
    status: "read" 
  },
  { id: 6, 
    dateTime: "04-23-24  11:49 AM", 
    message:"You have feedback. Check it now.", 
    status: "read" 
  },
];

export const Accounts = [
  { id: 20000000, 
    name: "Raul Tolentino", 
    role:"Security", 
    department: "",
  },
  { id: 20000001, 
    name: "Princess Dimagiba", 
    role:"Security", 
    department: "",
  },
  { id: 20000002, 
    name: "Maira Bermudez", 
    role:"Admin", 
    department: "CBA",
  },
  { id: 20000003, 
    name: "Juan Dela Cruz", 
    role:"Admin", 
    department: "COE",
  },
  { id: 20000004, 
    name: "Maribel Garcia", 
    role:"Admin", 
    department: "CICS",
  },
];

export const sched = [
  { id: 1,
    name: "Raul Tolentino", 
    couseCode: "",
    section:"", 
    day: "Monday",
    beginTime: "7:00 AM",
    endTime: "6:00 PM",
  },
  { id: 2,
    name: "Juan Dela Cruz", 
    couseCode: "IT 101",
    section:"BSIT 1A", 
    day: "Tuesday",
    beginTime: "8:00 AM",
    endTime: "11:00 AM",
  },
  { id: 3,
    name: "Marc Alfaro", 
    couseCode: "IT 401",
    section:"BSIT 4D", 
    day: "Tuesday",
    beginTime: "1:00 PM",
    endTime: "4:00 PM",
  },
];

export const roomHeader = [
  {id: 1,
   headers: "roomName",
  },
  {id: 2,
    headers: "building",
   },
   {id: 3,
    headers: "floor",
   },
   {id: 4,
    headers: "WithTv",
   },
   {id: 5,
    headers: "isLecture",
   },
   {id: 6,
    headers: "isLaboratory",
   },
   {id: 7,
    headers: "isAirconed",
   },
   {id: 8,
    headers: "capacity",
   },
   {id: 9,
    headers: "electricFans",
   },
   {id: 10,
    headers: "functioningComputers",
   },
   {id: 11,
    headers: "notFunctioningComputers",
   },
   {id: 12,
    headers: "status",
   },
   {id: 13,
    headers: "disable",
   },
]
export const roomDetails = [
  { id: 1,
    roomName: "101", 
    building: "CBA",
    floor:"1st Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 2,
    roomName: "102", 
    building: "CBA",
    floor:"1st Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 3,
    roomName: "103", 
    building: "CBA",
    floor:"1st Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 4,
    roomName: "201", 
    building: "CBA",
    floor:"2nd Floor", 
    WithTv: false,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 5,
    roomName: "202", 
    building: "CBA",
    floor:"2nd Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 6,
    roomName: "203", 
    building: "CBA",
    floor:"2nd Floor", 
    WithTv: false,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 7,
    roomName: "301", 
    building: "CBA",
    floor:"3rd Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 8,
    roomName: "302", 
    building: "CBA",
    floor:"3rd Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 2,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 9,
    roomName: "303", 
    building: "CBA",
    floor:"3rd Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 3,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 10,
    roomName: "401", 
    building: "CBA",
    floor:"4th Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 11,
    roomName: "402", 
    building: "CBA",
    floor:"4th Floor", 
    WithTv: false,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 2,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
  { id: 12,
    roomName: "403", 
    building: "CBA",
    floor:"4th Floor", 
    WithTv: true,
    isLecture: true,
    isLaboratory: false,
    isAirconed: false,
    capacity: 60,
    electricFans: 4,
    functioningComputers: 0,
    notFunctioningComputers: 0,
    status: "AVAILABLE",
    disable: false,
  },
];