name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - 'prisma/migrations/**'  # Only run this workflow when migrations are updated

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Adjust based on your project setup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Check for Prisma Migrations Changes
        id: prisma_changes
        run: |
          echo "::set-output name=changes::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^prisma/migrations/')"

      - name: Run Prisma Migrate Deploy
        if: ${{ steps.prisma_changes.outputs.changes != '' }}
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Ensure DATABASE_URL is set in your repo secrets
